### ISSUE TITLE
Tokenizer for CodeT5

### ISSUE THREAD

**Issue by GuodongFan** [awsm-research/VulRepair#2]
Hi there! Your work is excellent, but there is a problem. In my mind, the T5code model is pre-trained with a BPE tokenizer but fine-tuned with word level or BPE. Is there a GAP between the pre-trained BPE and word-level tokenizer? Will pre-trained models be ineffective when fine-tuning with word-level tokenizers?

**Comment by MichaelFu1998-create** [comment]
Hi @GuodongFan,
You're correct that using a word-level tokenizer to fine-tune CodeT5 could affect the model performance.
To empirically investigate whether the pre-trained weights in CodeT5 can still boost the performance when using a word-level tokenizer, i.e., to answer your question, **"Will pre-trained models be ineffective when fine-tuning with word-level tokenizers?"**, you may compare (1) fine-tune CodeT5 checkpoint with a word-level tokenizer and (2) fine-tune CodeT5 architecture but **randomly initialize the weights** (instead of using pre-trained weights of CodeT5) with a word-level tokenizer.

**Comment by GuodongFan** [comment]
Ok, thanks, I see.  But why the performance of the word level + no pre-train T5 is completely ineffective?
